import { Organization } from './types';

export const mockOrgs: Organization[] = [
  {
    id: 'ORG-001',
    name: 'Apex Legal Group',
    email: 'admin@apexlegal.com',
    createdDate: '2024-03-15',
    status: 'Active',
    planType: 'Subscription',
    planName: 'Professional',
    planExpiry: '2026-04-15',
    industry: 'Legal Services',
    phone: '+1 (555) 201-4400',
    address: '200 Park Ave, New York, NY 10166',
    adminCount: 3,
    docUsed: 8200,
    docTotal: 10000,
    admins: [
      { id: 'a1', name: 'John Carter', email: 'john@apexlegal.com', role: 'Admin', status: 'Active' },
      { id: 'a2', name: 'Lisa Monroe', email: 'lisa@apexlegal.com', role: 'Admin', status: 'Active' },
      { id: 'a3', name: 'Tom Reeves', email: 'tom@apexlegal.com', role: 'Admin', status: 'Inactive' },
    ],
    billingHistory: [
      { date: '2026-03-01', amount: '$149', description: 'Professional Plan - Monthly', status: 'Paid' },
      { date: '2026-02-01', amount: '$149', description: 'Professional Plan - Monthly', status: 'Paid' },
    ],
  },
  {
    id: 'ORG-002',
    name: 'Harrington & Co.',
    email: 'billing@harrington.co',
    createdDate: '2023-11-08',
    status: 'Active',
    planType: 'Subscription',
    planName: 'Enterprise',
    planExpiry: '2026-11-08',
    industry: 'Finance',
    phone: '+1 (555) 302-8800',
    address: '1 Financial Center, Boston, MA 02111',
    adminCount: 5,
    docUsed: 42100,
    docTotal: 50000,
    admins: [
      { id: 'a4', name: 'Rachel Kim', email: 'rachel@harrington.co', role: 'Admin', status: 'Active' },
      { id: 'a5', name: 'David Park', email: 'david@harrington.co', role: 'Admin', status: 'Active' },
    ],
    billingHistory: [
      { date: '2026-03-01', amount: '$699', description: 'Enterprise Plan - Monthly', status: 'Paid' },
      { date: '2026-02-01', amount: '$699', description: 'Enterprise Plan - Monthly', status: 'Paid' },
    ],
  },
  {
    id: 'ORG-003',
    name: 'Coastal Insurance',
    email: 'ops@coastalins.com',
    createdDate: '2025-01-20',
    status: 'Active',
    planType: 'Manual',
    planName: '1 Year Plan',
    planExpiry: '2026-01-20',
    industry: 'Insurance',
    phone: '+1 (555) 410-5500',
    address: '500 Ocean Dr, Miami, FL 33139',
    adminCount: 2,
    docUsed: 3400,
    docTotal: 5000,
    admins: [{ id: 'a6', name: 'Maria Santos', email: 'maria@coastalins.com', role: 'Admin', status: 'Active' }],
    billingHistory: [{ date: '2025-01-20', amount: '$1,800', description: 'Manual Plan - 1 Year', status: 'Paid' }],
  },
  {
    id: 'ORG-004',
    name: 'BlueSky Analytics',
    email: 'ops@blueskyanalytics.io',
    createdDate: '2025-08-05',
    status: 'Inactive',
    planType: 'Subscription',
    planName: 'Starter',
    planExpiry: '2025-11-05',
    industry: 'Technology',
    phone: '+1 (555) 900-1100',
    address: '77 Innovation Way, Seattle, WA 98101',
    adminCount: 1,
    docUsed: 2000,
    docTotal: 2000,
    admins: [{ id: 'a7', name: 'Alex Blue', email: 'alex@blueskyanalytics.io', role: 'Admin', status: 'Inactive' }],
    billingHistory: [{ date: '2025-10-01', amount: '$49', description: 'Starter Plan - Monthly', status: 'Failed' }],
  },
];
